name: github pages (build & deploy)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install deps
        run: npm ci

      - name: build
        run: npm run build

      - name: copy CNAME (if exists)
        run: |
          if [ -f CNAME ]; then cp CNAME dist/CNAME; fi

      - name: configure pages
        uses: actions/configure-pages@v3

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: deploy to github pages
        uses: actions/deploy-pages@v1