name: pages (vite build + deploy)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy CNAME if present
        run: |
          if [ -f CNAME ]; then cp CNAME dist/CNAME; fi
          if [ -f public/CNAME ]; then cp public/CNAME dist/CNAME; fi

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
